#### Data Ingestion

In [87]:
import pandas as pd

In [89]:
df = pd.read_csv(r"C:\Users\Admin\Documents\DataAnalysis\1py-master\py-master\ML\5_one_hot_encoding\homeprices.csv")
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

#### Pandas Get Dummies method - To handle categorical data

In [94]:
dummies = pd.get_dummies(df['town'])
dummies

    monroe township  robinsville  west windsor
0              True        False         False
1              True        False         False
2              True        False         False
3              True        False         False
4              True        False         False
5             False        False          True
6             False        False          True
7             False        False          True
8             False        False          True
9             False         True         False
10            False         True         False
11            False         True         False
12            False         True         False

### Adding the Neumerical data into orignal dataframe

In [101]:
merged_df = pd.concat([df,dummies], axis = 1)
merged_df

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

### Remove the town column

In [108]:
df_2 = merged_df.drop('town', axis = 1)

In [110]:
df_2

    area   price  monroe township  robinsville  west windsor
0   2600  550000             True        False         False
1   3000  565000             True        False         False
2   3200  610000             True        False         False
3   3600  680000             True        False         False
4   4000  725000             True        False         False
5   2600  585000            False        False          True
6   2800  615000            False        False          True
7   3300  650000            False        False          True
8   3600  710000            False        False          True
9   2600  575000            False         True         False
10  2900  600000            False         True         False
11  3100  620000            False         True         False
12  3600  695000            False         True         False

In [112]:
### define independent feature

X = df_2.drop('price' , axis = 1)
X

    area  monroe township  robinsville  west windsor
0   2600             True        False         False
1   3000             True        False         False
2   3200             True        False         False
3   3600             True        False         False
4   4000             True        False         False
5   2600            False        False          True
6   2800            False        False          True
7   3300            False        False          True
8   3600            False        False          True
9   2600            False         True         False
10  2900            False         True         False
11  3100            False         True         False
12  3600            False         True         False

In [114]:
### define target variable

y = df_2['price']
y

0     550000
1     565000
2     610000
3     680000
4     725000
5     585000
6     615000
7     650000
8     710000
9     575000
10    600000
11    620000
12    695000
Name: price, dtype: int64

In [116]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [118]:
model.fit(X, y)

LinearRegression()

In [122]:
y_pred = model.predict(X)
y_pred

array([539709.73984091, 590468.71640508, 615848.20468716, 666607.18125133,
       717366.1578155 , 579723.71533005, 605103.20361214, 668551.92431735,
       706621.15674047, 565396.15136531, 603465.38378844, 628844.87207052,
       692293.59277574])

In [126]:
df_2['Predicted Price'] = y_pred

In [128]:
df_2

    area   price  monroe township  robinsville  west windsor  Predicted Price
0   2600  550000             True        False         False    539709.739841
1   3000  565000             True        False         False    590468.716405
2   3200  610000             True        False         False    615848.204687
3   3600  680000             True        False         False    666607.181251
4   4000  725000             True        False         False    717366.157816
5   2600  585000            False        False          True    579723.715330
6   2800  615000            False        False          True    605103.203612
7   3300  650000            False        False          True    668551.924317
8   3600  710000            False        False          True    706621.156740
9   2600  575000            False         True         False    565396.151365
10  2900  600000            False         True         False    603465.383788
11  3100  620000            False         True         False    628844.872071
12  3600  695000            False         True         False    692293.592776

In [130]:
model.score(X,y)

0.9573929037221873